### ISSUE TITLE
In-accurate linear algebra.

### ISSUE THREAD

**Issue by PrawiraGenestonlia** [lordidiot/OpenGovSalary#1]
The linear algebra is not accurate. Taking 

<img width="512" alt="image" src="https://github.com/lordidiot/OpenGovSalary/assets/25548257/ace19a3a-0a01-4ca9-9602-967586c88f74">

as example,

You should not just consider `PM + 3 ENG + 1 D + 1 OPS + 1/3 POL`. This is because each of the function members have different titles. You should get a more granular title of each individuals from https://www.open.gov.sg/about-us/eng, for instance, Software Engineer vs Senior Software Engineer vs Lead Software Engineer. 

To get more accurate result, you have to:
1. Solve linear algebra for each role
2. Given loop through all employees in https://www.open.gov.sg/about-us/ and assign the salary solved in (1) to every individuals.

**Comment by lordidiot** [comment]
Thank you for the feedback!
Not super clear what you mean though, at the moment I'm treating each person as it's own variable to solve, i.e. I'm not lumping engineers together:

```python
    A = []
    Y = []
    for product_info in product_infos:
        _ = [0] * len(people)
        product_members = product_info.people
        for i, person in enumerate(people):
            if person in product_members:
                _[i] = product_members[person]
            
        Y.append(product_info.quarterly_manpower)
        A.append(_)
```

In that sense this equation `PM + 3 ENG + 1 D + 1 OPS + 1/3 POL` is not what is happening in my calculations. Perhaps I am misunderstanding what you mean?

**Comment by PrawiraGenestonlia** [comment]
Yep. My suggestion is to not treat each person uniquely. Solve it from their role perspective and work backwards to assign the salary to the person. You can try and compare the difference between the two results.

**Comment by lordidiot** [comment]
Thank you! That makes sense, so this is assuming that across equal titles the pays are close to identical?

**Comment by PrawiraGenestonlia** [comment]
Yes. It should give you average salary for each title (similar to https://www.levels.fyi/). The reason why this makes more sense because your system of linear equations will be much more accurate with least squares compared to treating individual because you will not have enough overlaps to produce accurate result.
